pipeline:
  scp:
    image: appleboy/drone-scp
    host: 172.28.128.100
    username: vagrant
    password: vagrant
    port: 22
    target: /home/vagrant
    source: /ansible
    when: master

  execute_ansible:
    image: appleboy/drone-ssh
    host: 172.28.128.100
    username: vagrant
    password: vagrant
    port: 22
    script:
      - cd /home/vagrant
      - ansible-playbook -v ansible/portainer.yml
    when: master
