- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Install Pip.
      apt: name=python-pip state=present
      become: yes

    - name: Install Docker Python library.
      pip: name=docker-py state=present
      become: yes

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce

    - name: Add vagrant user to docker group.
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes